"""init: sys_user table

Revision ID: 4a9c630f396a
Revises: 
Create Date: 2026-07-28 19:40:22.248834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9c630f396a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 哈希'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True, comment='bcrypt 哈希'),
    sa.Column('api_key_prefix', sa.String(length=12), nullable=True, comment='展示用前缀 sk-intellikb'),
    sa.Column('api_key_expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('api_key_last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.Column('api_key_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user')
    # ### end Alembic commands ###
