"""phase1: sys_kb + sys_document + sys_chunk

Revision ID: 68834020afef
Revises: 4a9c630f396a
Create Date: 2026-07-29 00:34:16.365362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68834020afef'
down_revision: Union[str, None] = '4a9c630f396a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='所属文档 ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='分块序号（从 0 开始）'),
    sa.Column('content', sa.Text(), nullable=False, comment='分块文本内容'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Token 数量估算'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False, comment='所属知识库 ID'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='原始文件名'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件类型: pdf/docx/md/txt'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态: uploading/parsing/chunking/indexing/done/error'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='分块数量'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_kb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='所有者用户 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开'),
    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='分块大小（字符）'),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False, comment='分块重叠（字符）'),
    sa.Column('embedding_model', sa.String(length=100), nullable=False, comment='Embedding 模型名'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_kb')
    op.drop_table('sys_document')
    op.drop_table('sys_chunk')
    # ### end Alembic commands ###
